### PR TITLE
feat: Migrate out of legacy module configuration

### PR DESCRIPTION
**Pull request by chrishiste**
Converts the module into a [non-legacy](https://developer.hashicorp.com/terraform/language/modules/develop/providers#legacy-shared-modules-with-provider-configurations) module by removing any provider configuration. The config will come from the parent module. I also fixed linting issues.

### CODE REVIEW

**Review by dlachasse — CHANGES_REQUESTED** [review]
Only change I can see that needs to be made here is to remove the zone from the list of variables [in the example](https://github.com/wandb/terraform-google-dagster/blob/9e92fbf071dafd6fefc32fabdc020c79550fbfad/example-app/variables.tf#L11-L14).

**Comment by chrishiste** [comment]
@dlachasse I left that zone variable purposely in the example because it requires to be set in the provider configuration as you can see [here](https://github.com/wandb/terraform-google-dagster/pull/12/files#diff-2019a724cc31ab45404d8be2d3f02b3805792895c35f7a4696a4ddd9259dc0e4L17).

ScreenShot 2023-08-14 at 19 57 49@2x

I removed it from the rest of the code because it was never used. The zone defaults to the provider one anyways.

**Comment by dlachasse** [comment]
> @dlachasse I left that zone variable purposely in the example because it requires to be set in the provider configuration as you can see [here](https://github.com/wandb/terraform-google-dagster/pull/12/files#diff-2019a724cc31ab45404d8be2d3f02b3805792895c35f7a4696a4ddd9259dc0e4L17).
> 
> ScreenShot 2023-08-14 at 19 57 49@2x
> I removed it from the rest of the code because it was never used. The zone defaults to the provider one anyways.

Ah TIL, thanks for the details. LGTM!

**Review by dlachasse — APPROVED** [review]

**Comment by jsbroks** [comment]
This PR is included in version 2.2.0 :tada:

**Pull request merged**
